[workspace]
authors = ["benson lee <benson106075@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "pixi-project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
run_python = "python ./src/hello.py"
run_samtools = "./src/samtools_test.sh"
run_R = "Rscript ./src/demo_ggplot.R"

[dependencies]
python = ">=3.14.3,<3.15"
cowpy = ">=1.1.5,<2"
numpy = ">=2.4.2,<3"
r-base = ">=4.5.2,<4.6"
r-ggplot2 = ">=4.0.2,<5"
samtools = ">=1.22.1,<2"
