project:
  type: website
  render:
    - "*.qmd"
    - "!**/*.Rmd"

website:
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
        icon: house
      - text: NGS Tools
        icon: tools
        menu:
          - href: ngs-tools/fastp.qmd
            text: fastp
          - href: ngs-tools/fastqc.qmd
            text: fastqc
          - href: ngs-tools/multiqc.qmd
            text: multiqc
          - href: ngs-tools/samtools.qmd
            text: samtools
          - href: ngs-tools/vcftools.qmd
            text: vcftools
          - href: ngs-tools/bcftools.qmd
            text: bcftools
      - text: Environment
        icon: boxes
        menu:
          - href: env-tools/conda.qmd
            text: conda
          - href: env-tools/mamba.qmd
            text: mamba
      - text: R
        icon: braces
        menu:
          - href: ngs-r/maftools.qmd
            text: maftools
      - text: Reports
        icon: file-earmark-bar-graph
        menu:
          - href: report/fastp_report.qmd
            text: fastp demo report
          - href: report/fastqc_report.qmd
            text: fastqc demo report
          - href: report/multiqc_report.qmd
            text: multiqc demo report

    tools:
      - icon: book
        text: GitBook
        href: https://benson1231.gitbook.io/benson1231-docs
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/benson1231/tools
          - text: Report a Bug
            href: https://github.com/benson1231/tools/issues

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css

    toc: true
    toc-title: Contents
    toc-location: left
    toc-depth: 4
    toc-expand: 1

    other-links:
      - text: Home
        icon: house
        href: https://benson1231.github.io/tools/

    code-links:
      - text: GitHub Repo
        icon: github
        href: https://github.com/benson1231/tools

execute: 
  enabled: false  
number-sections: true
