project:
  type: website
  render:
    - "*.qmd"
    - "!**/*.Rmd"
execute: 
  enabled: false  
number-sections: true
date-format: "YYYY-MM-DD"

format:
  html:
    css: styles/styles.css
    include-after-body:
      - includes/lightbox.html
    theme: 
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    toc: true
    toc-title: Contents
    toc-location: left
    toc-depth: 4
    toc-expand: 1
    other-links:
      - text: Home
        icon: house
        href: https://benson1231.github.io/tools/
    code-links:
      - text: GitHub Repo
        icon: github
        href: https://github.com/benson1231/tools

website:
  site-url: "https://benson1231.github.io/tools/"
  back-to-top-navigation: true
  page-footer: "Copyright 2026, benson1231"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
        icon: house

      - text: CI/CD
        icon: boxes
        menu:
          - href: cicd/linux.qmd
            text: linux
          - href: cicd/conda.qmd
            text: conda
          - href: cicd/mamba.qmd
            text: mamba
          - href: cicd/docker.qmd
            text: docker
          - href: cicd/github-actions.qmd
            text: github actions
          - href: cicd/kubernetes.qmd
            text: kubernetes
      - text: NGS Tools
        icon: tools
        menu:
          - text: preprocessing
          - href: tools/fastp.qmd
            text: fastp
          - href: tools/fastqc.qmd
            text: fastqc
          - href: tools/multiqc.qmd
            text: multiqc
          - href: tools/samtools.qmd
            text: samtools
          - href: tools/vcftools.qmd
            text: vcftools
          - href: tools/bcftools.qmd
            text: bcftools
          - href: tools/bedtools.qmd
            text: bedtools
            
          - text: others
          - href: tools/md5sum.qmd
            text: md5sum

      - text: R Tools
        icon: braces
        menu:
          - href: r/maftools/maftools.qmd
            text: maftools

      - text: Reports
        icon: file-earmark-bar-graph
        menu:
          - href: report/fastp_report.qmd
            text: fastp demo report
          - href: report/fastqc_report.qmd
            text: fastqc demo report
          - href: report/multiqc_report.qmd
            text: multiqc demo report

      - text: Workflow
        icon: diagram-3
        menu:
          - text: RNA-Seq with replicates
          - href: workflow/rnaseq-with-replicates-limma/rnaseq-with-replicates-limma.qmd
            text: rnaseq-with-replicates-limma
          - href: workflow/rnaseq-with-replicates-deseq2/rnaseq-with-replicates-deseq2.qmd
            text: rnaseq-with-replicates-deseq2

          - text: RNA-Seq without replicates
          - href: workflow/rnaseq-no-replicates-edger/rnaseq-no-replicates-edger.qmd
            text: rnaseq-no-replicates-edger

          - text: Others
          - href: workflow/survival-analysis-r/survival-analysis-r.qmd
            text: survival analysis


    tools:
      - icon: book
        text: GitBook
        href: https://benson1231.gitbook.io/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/benson1231/tools
          - text: Report a Bug
            href: https://github.com/benson1231/tools/issues
