project:
  type: website
  render:
    - "*.qmd"
    - "!**/*.Rmd"

website:
  site-url: "https://benson1231.github.io/tools/"
  back-to-top-navigation: true
  page-footer: "Copyright 2026, benson1231"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
        icon: house

      - text: CI/CD
        icon: boxes
        menu:
          - href: scripts/cicd/linux.qmd
            text: linux
          - href: scripts/cicd/conda.qmd
            text: conda
          - href: scripts/cicd/mamba.qmd
            text: mamba
          - href: scripts/cicd/docker.qmd
            text: docker
          - href: scripts/cicd/github-actions.qmd
            text: github actions
          - href: scripts/cicd/kubernetes.qmd
            text: kubernetes

      - text: NGS Tools
        icon: tools
        menu:
          - href: scripts/tools/fastp.qmd
            text: fastp
          - href: scripts/tools/fastqc.qmd
            text: fastqc
          - href: scripts/tools/multiqc.qmd
            text: multiqc
          - href: scripts/tools/samtools.qmd
            text: samtools
          - href: scripts/tools/vcftools.qmd
            text: vcftools
          - href: scripts/tools/bcftools.qmd
            text: bcftools
          - href: scripts/tools/bedtools.qmd
            text: bedtools
          - href: scripts/tools/md5sum.qmd
            text: md5sum

      - text: R Tools
        icon: braces
        menu:
          - href: scripts/r/maftools/maftools.qmd
            text: maftools

      - text: Reports
        icon: file-earmark-bar-graph
        menu:
          - href: scripts/report/fastp_report.qmd
            text: fastp demo report
          - href: scripts/report/fastqc_report.qmd
            text: fastqc demo report
          - href: scripts/report/multiqc_report.qmd
            text: multiqc demo report

      - text: Workflow
        icon: diagram-3
        menu:
          - href: scripts/workflow/survival-analysis-r/survival-analysis-r.qmd
            text: survival analysis

    tools:
      - icon: book
        text: GitBook
        href: https://benson1231.gitbook.io/benson1231-scripts
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/benson1231/tools
          - text: Report a Bug
            href: https://github.com/benson1231/tools/issues

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css

    toc: true
    toc-title: Contents
    toc-location: left
    toc-depth: 4
    toc-expand: 1

    other-links:
      - text: Home
        icon: house
        href: https://benson1231.github.io/tools/

    code-links:
      - text: GitHub Repo
        icon: github
        href: https://github.com/benson1231/tools

execute: 
  enabled: false  
number-sections: true
