project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: NGS Tools
        menu:
          - href: ngs-tools/fastp.qmd
            text: fastp
          - href: ngs-tools/fastqc.qmd
            text: fastqc
          - href: ngs-tools/multiqc.qmd
            text: multiqc
          - href: ngs-tools/samtools.qmd
            text: samtools
          - href: ngs-tools/vcftools.qmd
            text: vcftools
          - href: ngs-tools/bcftools.qmd
            text: bcftools
      - text: Environment Tools
        menu:
          - href: env-tools/conda.qmd
            text: conda
          - href: env-tools/mamba.qmd
            text: mamba
      - text: R Packages
        menu:
          - href: ngs-r/maftools/maftools.html
            text: maftools
      - text: Reports demo
        menu:
          - href: examples/fastp_report.html
            text: fastp demo report
          - href: examples/a.chr21_R1_fastqc.html
            text: fastqc demo report
          - href: examples/multiqc_report.html
            text: multiqc demo report

    tools:
      - icon: book
        text: GitBook
        href: https://benson1231.gitbook.io/benson1231-docs
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/benson1231/tools
          - text: Report a Bug
            href: https://github.com/benson1231/tools/issues

format:
  html:
    theme: cosmo
    css: styles/quarto.css

    toc: true
    toc-title: Contents
    toc-location: left
    toc-depth: 4
    toc-expand: 1

    other-links:
      - text: Home
        icon: house
        href: https://benson1231.github.io/tools/

    code-links:
      - text: GitHub Repo
        icon: github
        href: https://github.com/benson1231/tools

execute: 
  enabled: false  
number-sections: true
