on:
  workflow_dispatch:
  push:
    branches: main

name: Build and Deploy Website

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: envs/envs.yaml
          environment-name: bio-tools
          cache-environment: true

      - name: Show micromamba environment
        run: |
          echo "=== Micromamba Environment ==="
          which micromamba
          micromamba --version
          micromamba env list
          echo "================================"

      - name: Render Quarto website
        run: >
          micromamba run -n bio-tools
          quarto render website/

      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
